### ISSUE TITLE
What if MySQL server is not started and client trying to login?

### ISSUE THREAD

**Issue by kirsun** [cyberinferno/inferno-emu-v2#15]
I had a weired problem that, two three days back I forgot to start MySQL server and executed node with main.js. When I tried to login the client stuck. No message, nothing. When checking ,I found MySQL was not started. 

So I thought to add a check in helper > dB >  executeQuery   and just before getConnection, which send out message to client as "Server offline. Try again.". Its working now. 

Main problem is, how do I show you the modifications as my knowledge is very very thin on git system.
Any suggestions?

**Comment by cyberinferno** [comment]
You commit and push code to your github repository. Then give my repository
a pull request.

**Comment by kirsun** [comment]
Instead of touching deep into the db.js, I have worked for a simple and effective way by adding as below in login.js 

```
socket.on('data', function (data) {
    if(packet.helper.validatePacketSize(data, data.length)){
	  if(server.db.connectionPool.isPrepared){
		. . . 
                 . . . . . 
	  }
	  else
	  {
		socket.write(packet.helper.getPreLoginMessagePacket('Server Offline. Try Again.'));  	
	  }
```

**Comment by kirsun** [comment]
I have added the message as I told you above. I have attached some files to this reply. please check with your server. Next, planning to create a new character.
[db.js & login.js.zip](https://github.com/cyberinferno/inferno-emu-v2/files/514752/db.js.login.js.zip)

Just stop your mysql and start node main.js first and try to login. Next, start mysql and try logging again. I dont know to add to github. Do i need to just upload the files?

**Comment by kirsun** [comment]
As you said, I tried to put in github. Please check once and tell me if anything is wrong . link is here https://github.com/kirsun/inferno-emu-v2

**Comment by cyberinferno** [comment]
I have added the connection check just after pooling and if no connection I have throw exception making it not possible to run server without database connection. Thank you for the valuable feedback!
